config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'visitors#index'
  get '/register' => "visitors#register"
  get '/account' => "users#show"
  get '/golfers_index' => 'golfers#index'
  get '/contest_index' => 'contest#index'
  get '/index_specific' => 'contest#index_specific'
  get '/golf_lineup_index' => 'golf_lineup#index'
  get '/auth/:provider/callback' => 'sessions#create'
  post '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/contest.rb
class Contest < ActiveRecord::Base
end

app/models/golf_lineup.rb
class GolfLineup < ActiveRecord::Base
end

app/models/golfer.rb
class Golfer < ActiveRecord::Base
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
	attr_accessor :dk_username
end

app/models/user.rb
class User < ActiveRecord::Base

  before_create {generate_token(:auth_token)}

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.screenName = auth['info']['nickname']
      user.email = auth['info']['email'] #twitter doesn't disclose this - will be nil
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

  def generate_token(column)
    begin self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private 
    def require_login
      unless current_user
        redirect_to "/"
      end
    end

    def current_user
      begin
        @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find_by_auth_token!(cookies[:auth_token])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/contest_controller.rb
class ContestController < ApplicationController
	def index
		@contests = Contest.all
	end

	def index_specific
		@contests = Contest.where(:name => params[:name])
	end
end

app/controllers/golf_lineup_controller.rb
class GolfLineupController < ApplicationController
	def index
		@golf_lineups = GolfLineup.all
	end
end

app/controllers/golfers_controller.rb
class GolfersController < ApplicationController
	def index
		@golfers = Golfer.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  skip_before_filter :require_login

  def new
    redirect_to '/auth/twitter'
  end

  def create
    puts "HELLO IM IN SESSIONS CREATE"
    puts "REQUEST IS #{request.env["omniauth.auth"]}"
    auth = request.env["omniauth.auth"]
    puts "PROVIDER IS #{auth['provider']}"
    puts "UID IS #{auth['uid']}"
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    if params[:remember_me]
      cookies.permanent[:auth_token] = user.auth_token
    else
      cookies[:auth_token] = user.auth_token
    end
    redirect_to '/account', :notice => "signed"
  end

  def destroy
    cookies.delete(:auth_token)
    flash[:success] = "Signed Out!"
    redirect_to root_url
  end

  def failure
    redirect_to root_url, :notice => "invalid"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user?
  
  def show
    @user = User.find_by_auth_token!(cookies[:auth_token])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	skip_before_filter :require_login

	def index
		if user_signed_in?
			redirect_to "/account"
		end
	end

	def error
	end

	def register
		if user_signed_in?
			redirect_to "/account"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contest_helper.rb
module ContestHelper
end

app/helpers/golf_lineup_helper.rb
module GolfLineupHelper
end

app/helpers/golfers_helper.rb
module GolfersHelper
end

app/views/contest/index.html.erb
<div class="content container">
   <h2 class="page-title"><i>Live<span class="fw-semi-bold"> Contests</span></i></h2>
   <div class="row">
      <div class="col-md-11">
         <section class="widget">
            <br>
            <div class="table-responsive">
               <table class="table table-hover" id="table">
                  <thead>
                     <tr>
                        <th>Contest Name <i class="fa fa-ticket"></i></i></th>
                        <th>Type <i class="fa fa-database"></i></th>
                        <th>Entry Price <i class="fa fa-money"></i></th>
                        <th>Entries #</span></th>
                        <th>To Win %</th>
                        <th>Expected Payoff <i class="fa fa-ship"></i></th>
                        <th colspan="3"></th>
                     </tr>
                  </thead>
                  <tbody>
                     <% @contests.each do |contest| %> 
                     <tr>
                        <td><%= link_to contest.name, index_specific_path(:name => contest.name) %></td>
                        <td><%= link_to contest.contest_type, index_specific_path(:name => contest.name) %></td>
                        <td><%= link_to "$#{'%.2f' % contest.entry_price}", index_specific_path(:name => contest.name) %></td>
                        <td><%= link_to contest.num_entries, index_specific_path(:name => contest.name) %></td>
                        <td><%= link_to "#{'%.2f' % (contest.win*100.0).to_s}%", index_specific_path(:name => contest.name) %></td>
                        <td><%= link_to "$#{'%.2f' % contest.expected_payoff.to_s}", index_specific_path(:name => contest.name) %></td>
                     </tr>
                     <% end %>
                  </tbody>
               </table>
            </div>
      </div>
      </section>
   </div>
</div>

app/views/contest/index_specific.html.erb
<div class="content container">
   <h2 class="page-title"><i><%= @contests.first.name %></i></h2>
   <div class="row">
      <div class="col-md-11">
         <section class="widget">
            <br>
            <div class="table-responsive">
               <table class="table table-hover" id="table">
                  <thead>
                     <tr>
                        <th>Type <i class="fa fa-database"></i></th>
                        <th>Entry Price <i class="fa fa-money"></i></th>
                        <th>Entries #</span></th>
                        <th>To Win %</th>
                        <th>Expected Payoff <i class="fa fa-ticket"></i></th>
                        <th colspan="3"></th>
                     </tr>
                  </thead>
                  <tbody>
                     <% @contests.each do |contest| %> 
                     <tr>
                        <td><%=contest.contest_type%></td>
                        <td>$<%='%.2f' % contest.entry_price%></td>
                        <td><%=contest.num_entries%></td>
                        <td><%= '%.2f' % (contest.win*100.0).to_s%>%</td>
                        <td>$<%= '%.2f' % contest.expected_payoff.to_s%></td>
                     </tr>
                     <% end %>
                  </tbody>
               </table>
            </div>
      </div>
      </section>
   </div>
</div>

app/views/golf_lineup/index.html.erb
<div class="content container">
  <div class="col-md-11">

  <div class="row">
    <div class="thumbnail">
        <img src="/assets/img/ball_sky.jpg" alt="">
    </div>
  </div>

  
  <div class="row" style="margin-left: -20px">
      <% lineup = @golf_lineups.first%>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <div class="box">
              <div class="icon">
                  <%= lineup.rank %>
              </div>
              <div class="description">
                  <span class="glyphicon glyphicon-upload"></span> Ranking 
              </div>
          </div>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <div class="box">
              <div class="big-text">
                  <%= lineup.dk_score %>
              </div>
              <div class="description">
                  <i class="fa fa-bar-chart"></i>
                  DraftKings Score
              </div>
          </div>
      </div>

      <div class="col-md-4 col-sm-4 col-xs-6">
          <div class="box">
              <div class="big-text" style="font-size: 26px">
                  <i class="fa fa-trophy"></i> Leading Lineup <i class="fa fa-trophy"></i>
              </div>
              <div class="description">
                  <p>Jordan Speith - Paul Casey - Emilio Grillo</p> <p>Ricky Fowler - Hideki Masuyama -  Keegan Bradley</p>
              </div>
          </div>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <div class="box">
              <div class="big-text" style="font-size: 26px">
                  $<%= '%.2f' % lineup.expected_payout %>
              </div>
              <div class="description">
                  Equity
                  <i class="fa fa-money"></i>
              </div>
          </div>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <div class="box">
              <div class="icon">
                  <%= '%.2f' % (lineup.probability_win*100) %>%</strong>
              </div>
              <div class="description">
                  Chance to <strong>Win</strong>
                  <i class="fa fa-ticket"></i>
              </div>
          </div>
      </div>
  </div>

  <br/>

  <i><h2 class="page-title" style="margin-left: -14px">Your <span class="fw-semi-bold">Lineups</span> <small>blah blah blah</small></i></h2></i>
  <div class="row">
        <section class="widget">
           <br>
           <div class="table-responsive">
              <table class="table table-hover" id="table">
                 <thead>
                    <tr>
                       <th>Rank <span class="glyphicon glyphicon-resize-vertical"></span></th>
                       <th>DK Score <i class="fa fa-bar-chart"></i></th>
                       <th>Lineup <i class="fa fa-trophy"></i></th>
                       <th>Win %</th>
                       <th>Make Cut %</th>
                       <th>MDF %</th>
                       <th>Expected Payout <i class="fa fa-money"></i></th>
                       <th colspan="3"></th>
                    </tr>
                 </thead>
                 <tbody>
                    <% @golf_lineups.each do |lineup| %> 
                    <tr>
                       <td><%= lineup.rank %></td>
                       <td><%= lineup.dk_score %></td>
                       <td>
                        <div class="col-md-12 move">
                          <div class="panel-group" id="accordion3">
                              <div class="panel">
                                  <div class="panel-heading">
                                      <a class="accordion-toggle collapsed" id="lineup-drop" data-toggle="collapse" href="#collapseOneTwo">Golfers
                                      </a>
                                  </div>
                                  <div id="collapseOneTwo" class="panel-collapse collapse">
                                      <div class="panel-body" style="text-align: center">
                                        <ul>
                                          <li>Tiger Woods</li>
                                          <li>Jordan Spleth</li>
                                          <li>Jason Day</li>
                                          <li>Rory Mcllroy</li>
                                          <li>Bubba Watson</li>
                                          <li>Rickie Fowler</li>
                                        </ul>
                                          <br>
                                      </div>
                                  </div>
                              </div>
                          </div>
                       </td>
                       <td><%= '%.2f' % (lineup.probability_win*100) %>%</td>
                       <td><%= '%.2f' % (lineup.probability_mc*100) %>%</td>
                       <td><%= '%.2f' % (lineup.probability_mf*100) %>%</td>
                       <td>$<%= '%.2f' % (lineup.expected_payout.to_s) %></td>
                    </tr>
                    <% end %>
                 </tbody>
              </table>
           </div>
     </div>

     <i><h2 class="page-title" style="margin-left: -14px">Total <span class="fw-semi-bold">Lineups</span> <small>blah blah blah</small></i></h2></i>
  <div class="row">
        <section class="widget">
           <br>
           <div class="table-responsive">
              <table class="table table-hover" id="table">
                 <thead>
                    <tr>
                       <th>Rank <span class="glyphicon glyphicon-resize-vertical"></span></th>
                       <th>DK Score <i class="fa fa-bar-chart"></i></th>
                       <th>Lineup <i class="fa fa-trophy"></i></th>
                       <th>Win %</th>
                       <th>Make Cut %</th>
                       <th>MDF %</th>
                       <th>Expected Payout <i class="fa fa-thumbs-up"></i></th>
                       <th colspan="3"></th>
                    </tr>
                 </thead>
                 <tbody>
                    <% @golf_lineups.each do |lineup| %> 
                    <tr>
                       <td><%= lineup.rank %></td>
                       <td><%= lineup.dk_score %></td>
                       <td>
                        <div class="col-md-12 move">
                          <div class="panel-group" id="accordion3">
                              <div class="panel">
                                  <div class="panel-heading">
                                      <a class="accordion-toggle collapsed" id="lineup-drop" data-toggle="collapse" href="#collapseOneTwo">Golfers
                                      </a>
                                  </div>
                                  <div id="collapseOneTwo" class="panel-collapse collapse">
                                      <div class="panel-body" style="text-align: center">
                                        <ul>
                                          <li>Tiger Woods</li>
                                          <li>Jordan Spleth</li>
                                          <li>Jason Day</li>
                                          <li>Rory Mcllroy</li>
                                          <li>Bubba Watson</li>
                                          <li>Rickie Fowler</li>
                                        </ul>
                                          <br>
                                      </div>
                                  </div>
                              </div>
                          </div>
                       </td>
                       <td><%= lineup.probability_win*100 %>%</td>
                       <td><%= lineup.probability_mc*100 %>%</td>
                       <td><%= lineup.probability_mf*100 %>%</td>
                       <td>$<%= lineup.expected_payout.to_s %></td>
                    </tr>
                    <% end %>
                 </tbody>
              </table>
           </div>
     </div>
     </section>
  </div>
</div>

app/views/golfers/index.html.erb
<div class="content container">
  <div class="row">
    <div class="col-md-11">
          <div class="thumbnail">
              <img src="/assets/img/ball_sky.jpg" alt="">
          </div>
    </div>
  </div>
  <h2 class="page-title"><i><span class="fw-semi-bold"><%= @golfers.first.contest_name %></i></span></h2>
  <div class="row">
     <div class="col-md-11">
        <header>
           <div class="widget-controls">
              <div class="width-300">
                 <div id="extra-space" class="input-group input-group-sm input-group-transparent input-group-rounded">
                    <span class="input-group-addon">
                    <i class="fa fa-search"></i>
                    </span>
                    <input class="form-control input-transparent" id="search" type="text" placeholder="Search">
                 </div>
              </div>
           </div>
        </header>
        <section class="widget">
           <br>
           <div class="table-responsive">
              <table class="table table-hover" id="table">
                 <thead>
                    <tr>
                       <th>Rank <span class="glyphicon glyphicon-resize-vertical"></span></th>
                       <th>Name <span class="glyphicon glyphicon-user"></span></th>
                       <th>STP <span class="glyphicon glyphicon-fire"></span></th>
                       <th>Hole <span class="glyphicon glyphicon-pencil"></span></th>
                       <th>Win %</th>
                       <th>Make Cut %</th>
                       <th>MDF %</th>
                       <th>Stats <span class="glyphicon glyphicon-tasks"></span></th>
                       <th colspan="3"></th>
                    </tr>
                 </thead>
                 <tbody>
                    <% @golfers.each do |golfer| %> 
                    <tr>
                       <td><%= golfer.rank %></td>
                       <td><%= golfer.name %></td>
                       <td><%= golfer.score_to_par %></td>
                       <td><%= 'R' + golfer.last_update_round.to_s + ' : H' + golfer.last_update_hole.to_s %></td>
                       <td><%= ('%.1f' % (golfer.probability_win*100.0)).to_s. + '%' %></td>
                       <td><%= ('%.1f' % (golfer.probability_make_cut*100.0)).to_s + '%' %></td>
                       <td><%= ('%.1f' % (golfer.probability_mdf*100.0)).to_s + '%' %></td>
                       <% stats = golfer.stats.split("|")%>
                       <td> <span class="label label-success"><%= stats[0] %></span> 
                          <span class="label label-success"><%= stats[1] %></span> 
                          <span class="label label-warning"><%= stats[2] %></span>  
                          <span class="label label-danger"><%= stats[3] %></span>  
                          <span class="label label-danger"><%= stats[4] %></span>  
                       </td>
                       </td>
                    </tr>
                    <% end %>
                 </tbody>
              </table>
           </div>
     </div>
     </section>
  </div>
</div>

<script>
   // SEARCH FUNCTION
   var $rows = $('#table tbody tr');
   $('#search').keyup(function() {
       
       var val = '^(?=.*\\b' + $.trim($(this).val()).split(/\s+/).join('\\b)(?=.*\\b') + ').*$',
           reg = RegExp(val, 'i'),
           text;
       
       $rows.show().filter(function() {
           text = $(this).text().replace(/\s+/g, ' ');
           return !reg.test(text);
       }).hide();
   });
</script>

app/views/layouts/_navbar.html.erb
<body class="background-dark">
<div class="logo">
   <h4><a href="/account">Live <strong>Sweat</strong></a></h4>
</div>
<nav id="sidebar" class="sidebar nav-collapse collapse">
   <ul id="side-nav" class="side-nav">
     <li class="">
        <a href="/account"><i class="fa fa-home"></i> <span class="name">Your Account</span></a>
      </li>
      <li class="">
        <a href="/golfers_index"><i class="fa fa-group"></i> <span class="name">Leaderboard</span></a>
      </li>
      <li class="">
        <a href="/contest_index"><i class="fa fa-trophy"></i> <span class="name">Contests</span></a>
      </li>
      <li class="">
        <a href="/golf_lineup_index"><i class="fa fa-list"></i> <span class="name">Your Lineups</span></a>
      </li>
   </ul>
</nav>
<div class="wrap">
<header class="page-header">
   <div class="navbar">
      <ul class="nav navbar-nav navbar-right pull-right">
         <li class="divider"></li>
         <li class="hidden-xs">
            <a href="#" id="settings"
               title="Settings"
               data-toggle="popover"
               data-placement="bottom">
            <i class="fa fa-cog"></i>
            </a>
         </li>
         <li class="hidden-xs dropdown">
            <a href="#" title="Account" id="account"
               class="dropdown-toggle"
               data-toggle="dropdown">
            <i class="fa fa-user"></i>
            </a>
            <ul id="account-menu" class="dropdown-menu account" role="menu">
               <li role="presentation" class="account-picture">
                  <img src="img/2.jpg" alt="">
                  <%= User.find_by_auth_token!(cookies[:auth_token])[:name] %>
               </li>
               <li role="presentation">
                  <a href="/account" class="link">
                  <i class="fa fa-user"></i>
                  Profile
                  </a>
               </li>
               <li role="presentation">
                  <a href="component_calendar.html" class="link">
                  <i class="fa fa-calendar"></i>
                  Calendar
                  </a>
               </li>
            </ul>
         </li>
         <li class="visible-xs">
            <a href="#"
               class="btn-navbar"
               data-toggle="collapse"
               data-target=".sidebar"
               title="">
            <i class="fa fa-bars"></i>
            </a>
         </li>
         <li class="hidden-xs"><a href="/signout"><i class="fa fa-sign-out"></i></a></li>
      </ul>
   </div>
</header>
         

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Live Sweat</title>
      <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "DFS Albatross" %>">
      <!-- TEMPLATE CSS -->
      <link href="/assets/css/application.css" rel="stylesheet">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <meta name="author" content="">
      <meta charset="utf-8">
      <%= csrf_meta_tags %>
   </head>
   <body class="background-dark">

      <% if user_signed_in? %>
         <%= render 'layouts/navbar' %>
      <% end %>

         <!-- common libraries. required for every page-->
         <script src="/assets/lib/jquery/dist/jquery.min.js"></script>
         <script src="/assets/lib/jquery-pjax/jquery.pjax.js"></script>
         <script src="/assets/lib/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
         <script src="/assets/lib/widgster/widgster.js"></script>
         <script src="/assets/lib/underscore/underscore.js"></script>
         <!-- common application js -->
         <script src="/assets/js/app.js"></script>
         <script src="/assets/js/settings.js"></script>
         <!-- page specific libs -->
         <script src="/assets/lib/jquery.sparkline/index.js"></script>
         <script src="/assets/lib/messenger/build/js/messenger.js"></script>
        <script src="/assets/lib/messenger/build/js/messenger-theme-flat.js"></script>
         <script src="/assets/lib/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
        <script src="/assets/lib/underscore/underscore.js"></script>
        <script src="/assets/lib/backbone/backbone.js"></script>
        <script src="/assets/lib/backbone.paginator/lib/backbone.paginator.min.js"></script>
        <script src="/assets/lib/backgrid/lib/backgrid.min.js"></script>
        <script src="/assets/lib/backgrid-paginator/backgrid-paginator.js"></script>
        <script src="/assets/lib/datatables/media/js/jquery.dataTables.min.js"></script>

         <!-- page application js -->
         <script src="/assets/js/tables-static.js"></script>
         <script src="/assets/js/tables-dynamic.js"></script>
         <script src="/assets/js/ui-notifications.js"></script> 
         <%= yield %>

   </body>
</html>

app/views/users/show.html.erb
<% if flash[:notice] == "signed" %>
	<script>notification('Signed In!', 'success')</script>
<% end %>

<h3>Your Account</h3>
<p>Hello <%= @user.name %>!</p>

app/views/visitors/error.html.erb
<body class="background-dark">
        <div class="error-page container">
            <main id="content" class="error-container" role="main">
                <div class="row">
                    <div class="col-lg-4 col-sm-6 col-xs-10 col-lg-offset-4 col-sm-offset-3 col-xs-offset-1">
                        <div class="error-container">
                            <h1 class="error-code">404</h1>
                            <p class="error-info">
                                Opps, it seems that this page does not exist.
                            </p>
                            <p class="error-help mb">
                                If you are sure it should, search for it.
                            </p>
                            <div class="form-group">
                                <input class="form-control" type="text" placeholder="Search Pages">
                            </div>
                            <a href="special_search.html" class="btn btn-transparent">
                                Search <i class="fa fa-search text-warning ml-xs"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </main>

            <footer class="page-footer">
                &copy; 2015 - Biddrocket
            </footer>
        </div>
<!-- common libraries. required for every page-->
<script src="lib/jquery/dist/jquery.min.js"></script>
<script src="lib/jquery-pjax/jquery.pjax.js"></script>
<script src="lib/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
<script src="lib/widgster/widgster.js"></script>
<script src="lib/underscore/underscore.js"></script>

<!-- common application js -->
<script src="js/app.js"></script>
<script src="js/settings.js"></script>

<!-- common templates -->
<script type="text/template" id="settings-template">
    <div class="setting clearfix">
        <div>Background</div>
        <div id="background-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            <% dark = background == 'dark'; light = background == 'light';%>
            <button type="button" data-value="dark" class="btn btn-sm btn-default <%= dark? 'active' : '' %>">Dark</button>
            <button type="button" data-value="light" class="btn btn-sm btn-default <%= light? 'active' : '' %>">Light</button>
        </div>
    </div>
    <div class="setting clearfix">
        <div>Sidebar on the</div>
        <div id="sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            <% onRight = sidebar == 'right'%>
            <button type="button" data-value="left" class="btn btn-sm btn-default <%= onRight? '' : 'active' %>">Left</button>
            <button type="button" data-value="right" class="btn btn-sm btn-default <%= onRight? 'active' : '' %>">Right</button>
        </div>
    </div>
    <div class="setting clearfix">
        <div>Sidebar</div>
        <div id="display-sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            <% display = displaySidebar%>
            <button type="button" data-value="true" class="btn btn-sm btn-default <%= display? 'active' : '' %>">Show</button>
            <button type="button" data-value="false" class="btn btn-sm btn-default <%= display? '' : 'active' %>">Hide</button>
        </div>
    </div>
    <div class="setting clearfix">
        <div>White Version</div>
        <div>
            <a href="../white/index.html" class="btn btn-sm btn-default">&nbsp; Switch &nbsp;   <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
</script>

<script type="text/template" id="sidebar-settings-template">
    <% auto = sidebarState == 'auto'%>
    <% if (auto) {%>
    <button type="button"
            data-value="icons"
            class="btn-icons btn btn-transparent btn-sm">Icons</button>
    <button type="button"
            data-value="auto"
            class="btn-auto btn btn-transparent btn-sm">Auto</button>
    <%} else {%>
    <button type="button"
            data-value="auto"
            class="btn btn-transparent btn-sm">Auto</button>
    <% } %>
</script>

    <!-- page specific scripts -->


</body>